version: '3.7'

services:
    database_ignite:
     image: postgres
     restart: always
     container_name: database_ignite
     ports:
      - "HOST:CONTAINER"
      ##- 5432-5432 o comando acima vai associar o banco de dados a porta 5432 automaticamente
     environment:
     - POSTGRES_DB=rentcar
     - POSTGRES_USER=docker
     - POSTGRES_PASSWORD=ignite
     volumes:
      - pgdata:/data/postgres
     ##network_mode: host
    app:
     build: .
     container_name: rentcar
     command: npm run dev
     ports:
         - "3333:3333"
     volumes:
        - .:/users/app
     ##network_mode: host

volumes:
 pgdata:
  driver: local