version: "3.7"

services:
  db:
    image: postgres
    container_name: database_ignite
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentcar
    volumes:
      - pgdata:/data/postgres
    # network_mode: host

  app:
    build: .
    container_name: rentcar
    ports:
      - "8000:8000"
    volumes:
      - .:/users/app
    depends_on:
      - db
    # network_mode: host
  
  

volumes:
  pgdata:
    driver: local